# Generated by Django 5.1.1 on 2024-09-12 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_alter_cartitems_cart_alter_cartitems_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='womenimage',
            old_name='women',
            new_name='woman',
        ),
    ]
